# Generated by Django 4.0.4 on 2022-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
